# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:31:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Meta(BaseModel):
    BK_JOB_ID: Optional[str] = None
    BUILD_NUMBER: Optional[str] = None
    CIRCLE_BUILD_URL: Optional[str] = None
    CIRCLE_COMPARE_URL: Optional[str] = None
    COMMIT: Optional[str] = None
    GITHUB_SHA: Optional[str] = None
    TRAVIS_BUILD_WEB_URL: Optional[str] = None
    created_by: Optional[str] = Field(None, alias='created-by')
    created_by_1: Optional[str] = Field(None, alias='created_by')
    deploymentPrefix: Optional[str] = None
    gitSha: Optional[str] = None
    githubCommitAuthorLogin: Optional[str] = None
    githubCommitAuthorName: Optional[str] = None
    githubCommitMessage: Optional[str] = None
    githubCommitOrg: Optional[str] = None
    githubCommitRef: Optional[str] = None
    githubCommitRepo: Optional[str] = None
    githubCommitSha: Optional[str] = None
    githubDeployment: Optional[str] = None
    githubDeploymentAuthorizedBy: Optional[str] = None
    githubOrg: Optional[str] = None
    githubPrId: Optional[str] = None
    githubRepo: Optional[str] = None
    gitlabCommitAuthorAvatar: Optional[str] = None
    gitlabCommitAuthorLogin: Optional[str] = None
    gitlabCommitAuthorName: Optional[str] = None
    gitlabCommitMessage: Optional[str] = None
    gitlabCommitRef: Optional[str] = None
    gitlabCommitSha: Optional[str] = None
    gitlabDeployment: Optional[str] = None
    gitlabProjectId: Optional[str] = None
    gitlabProjectName: Optional[str] = None
    gitlabProjectNamespace: Optional[str] = None
    gitlabProjectPath: Optional[str] = None
    gl: Optional[str] = None
    targetDomain: Optional[str] = None
    useOldPipeline: Optional[str] = None


class Deployment(BaseModel):
    id: str = Field(..., description='Unique identifier of the deployment')
    meta: Meta
    name: str
    url: str


class Event(BaseModel):
    created: int
    createdAt: Optional[int] = None
    id: str
    ownerId: str
    region: Optional[str] = None
    teamId: Optional[str] = None
    userId: str


class Webhook(BaseModel):
    configurationId: str = Field(
        ...,
        description='An id that corresponds to the configuration that generated the token that was used to create the webhook',
    )
    createdAt: int = Field(
        ..., description='Timestamp that tells when was the webhook created'
    )
    events: List[str] = Field(
        ...,
        description='An array with the event identifiers that the webhook can receive',
    )
    id: str = Field(..., description='Id of the webhook')
    name: str = Field(
        ..., description='A name for the webhook that serves as a canonical description'
    )
    ownerId: Optional[str] = Field(
        None, description='Id of the owner which can be a user or a team'
    )
    url: str = Field(..., description='The URL where the POST request will be sent')


class V1IntegrationsWebhooksGetResponse(RootModel[List[Webhook]]):
    root: List[Webhook] = Field(
        ..., description='An Array of webhooks for the given account'
    )


class V1IntegrationsWebhooksPostRequest(BaseModel):
    name: str = Field(..., description='A name to assign to the webhook')
    url: str = Field(..., description='The URL ZEIT will post to when events happen')


class ServiceType(Enum):
    zeit_world = 'zeit.world'
    external = 'external'
    na = 'na'


class Domain(BaseModel):
    boughtAt: int = Field(
        ...,
        description='A timestamp to tell when the domain was purchase if it was purchased with ZEIT',
    )
    cdnEnabled: bool = Field(
        ..., description='Wether the Cloudfare CDN is enabled for the domain or not'
    )
    createdAt: int = Field(
        ..., description='A timestamp that shows when the domain was created'
    )
    expiresAt: int = Field(
        ..., description="The expiration date for the domain in case it's in ZEIT"
    )
    id: str = Field(..., description='The unique identifier of the domain.')
    intendedNameservers: List[str] = Field(
        ...,
        description='The set of nameservers ZEIT requires the user to set to verify the domain with Nameservers',
    )
    name: str = Field(..., description='The domain name including the TLD')
    nameservers: List[str] = Field(
        ..., description='The current nameservers we have detected for the domain'
    )
    nsVerifiedAt: int = Field(
        ...,
        description='The timestamp of the last time the domain was verified using Nameservers',
    )
    orderedAt: Optional[int] = Field(
        None,
        description='A timestamp indicating when the domain was ordered if it was purchased with ZEIT',
    )
    serviceType: ServiceType = Field(
        ..., description='Indicates the current DNS service the domain is using'
    )
    transferredAt: Optional[int] = Field(
        None,
        description='If the domain was transferred to ZEIT, it indicates the timestamp for when the transfer was started',
    )
    txtVerifiedAt: int = Field(
        ...,
        description='The timestamp of the last time the domain was verified using a TXT record',
    )
    verificationRecord: str = Field(
        ...,
        description='Indicates the verification record that should be used to verify the domain using a TXT record',
    )
    verified: bool = Field(
        ..., description='Indicates if the domain ownership was already verified'
    )


class V4DomainsGetResponse(BaseModel):
    domains: List[Domain] = Field(
        ..., description='An Array of domains for the given account'
    )


class Alias(BaseModel):
    alias: str
    created: int
    id: str


class Cert(BaseModel):
    cns: List[str]
    created: int
    id: str


class Creator(BaseModel):
    customerId: Optional[str] = None
    email: str
    id: str
    isDomainReseller: Optional[bool] = None
    username: str


class Domain1(BaseModel):
    aliases: List[Alias] = Field(
        ..., description='Collection of aliases where the domain is used.'
    )
    boughtAt: int = Field(
        ...,
        description='A timestamp to tell when the domain was purchase if it was purchased with ZEIT',
    )
    cdnEnabled: bool = Field(
        ..., description='Wether the Cloudfare CDN is enabled for the domain or not'
    )
    certs: List[Cert] = Field(..., description='Collection of certs for the domain')
    createdAt: int = Field(
        ..., description='A timestamp that shows when the domain was created'
    )
    creator: Creator = Field(..., description='Information about who added the domain')
    expiresAt: int = Field(
        ..., description="The expiration date for the domain in case it's in ZEIT"
    )
    id: str = Field(..., description='The unique identifier of the domain.')
    intendedNameservers: List[str] = Field(
        ...,
        description='The set of nameservers ZEIT requires the user to set to verify the domain with Nameservers',
    )
    name: str = Field(..., description='The domain name including the TLD')
    nameservers: List[str] = Field(
        ..., description='The current nameservers we have detected for the domain'
    )
    nsVerifiedAt: int = Field(
        ...,
        description='The timestamp of the last time the domain was verified using Nameservers',
    )
    orderedAt: Optional[int] = Field(
        None,
        description='A timestamp indicating when the domain was ordered if it was purchased with ZEIT',
    )
    serviceType: ServiceType = Field(
        ..., description='Indicates the current DNS service the domain is using'
    )
    suffix: bool = Field(
        ...,
        description='Tells if the domain is being used as a custom suffix for the user or team',
    )
    transferredAt: Optional[int] = Field(
        None,
        description='If the domain was transferred to ZEIT, it indicates the timestamp for when the transfer was started',
    )
    txtVerifiedAt: int = Field(
        ...,
        description='The timestamp of the last time the domain was verified using a TXT record',
    )
    verificationRecord: str = Field(
        ...,
        description='Indicates the verification record that should be used to verify the domain using a TXT record',
    )
    verified: bool = Field(
        ..., description='Indicates if the domain ownership was already verified'
    )


class V4DomainsNameGetResponse(BaseModel):
    domain: Domain1 = Field(..., description='The domain information')


class Code(Enum):
    not_found = 'not_found'


class Error(BaseModel):
    code: Code
    message: str
    name: str


class V4DomainsNameGetResponse1(BaseModel):
    error: Error
