# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:31:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel

from . import Deployment
from .Event import Event


class Payload(BaseModel):
    alias: str
    aliasId: Optional[str] = None
    deployment: Optional[Deployment] = None
    deploymentId: Optional[str] = None
    deploymentUrl: Optional[str] = None
    oldDeploymentId: Optional[str] = None
    ruleCount: Optional[int] = None


class Type(Enum):
    alias = 'alias'


class BodyUrlPostRequest(Event):
    payload: Payload
    type: Type


class Bru1(BaseModel):
    maxInstances: Optional[int] = None
    minInstances: Optional[int] = None


class Iad1(BaseModel):
    maxInstances: Optional[int] = None
    minInstances: Optional[int] = None


class Sfo1(BaseModel):
    maxInstances: Optional[int] = None
    minInstances: Optional[int] = None


class Scale(BaseModel):
    bru1: Optional[Bru1] = None
    iad1: Optional[Iad1] = None
    sfo1: Optional[Sfo1] = None


class TypeModel(Enum):
    NPM = 'NPM'
    STATIC = 'STATIC'
    DOCKER = 'DOCKER'
    LAMBDA = 'LAMBDA'


class PayloadModel(BaseModel):
    deployment: Optional[Deployment] = None
    deploymentId: Optional[str] = None
    name: str
    plan: Optional[str] = None
    project: Optional[str] = None
    regions: Optional[List[str]] = None
    scale: Optional[Scale] = None
    type: Optional[TypeModel] = None
    url: Optional[str] = None


class TypeModel1(Enum):
    deployment = 'deployment'


class TypeModel2(Enum):
    NPM = 'NPM'
    STATIC = 'STATIC'
    DOCKER = 'DOCKER'
    LAMBDA = 'LAMBDA'


class PayloadModel1(BaseModel):
    deployment: Deployment
    deploymentId: str
    name: str
    plan: str
    project: str
    regions: Optional[List[str]] = None
    type: TypeModel2
    url: str


class TypeModel3(Enum):
    deployment_error = 'deployment-error'


class TypeModel4(Enum):
    NPM = 'NPM'
    STATIC = 'STATIC'
    DOCKER = 'DOCKER'
    LAMBDA = 'LAMBDA'


class TypeModel5(Enum):
    deployment_ready = 'deployment-ready'


class PayloadModel2(BaseModel):
    domainId: Optional[str] = None
    name: str
    zoneId: Optional[float] = None


class TypeModel6(Enum):
    domain = 'domain'


class PayloadModel3(BaseModel):
    domainId: Optional[str] = None
    name: str


class TypeModel7(Enum):
    domain_delete = 'domain-delete'


class TypeModel8(Enum):
    domain_verify = 'domain-verify'
