# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:31:52+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    BaseSecurity,
    HTTPBearer,
    UnsuportedSecurityStub,
)
from fastapi import Query

from models import (
    V1IntegrationsWebhooksGetResponse,
    V1IntegrationsWebhooksPostRequest,
    V4DomainsGetResponse,
    V4DomainsNameGetResponse,
    V4DomainsNameGetResponse1,
    Webhook,
)
from models.field__request import BodyUrlPostRequest

app = MCPProxy(
    contact={'email': 'javi@zeit.co', 'name': 'Javi Velasco', 'url': 'zeit.co'},
    title='ZEIT API',
    version='v2019-01-07',
    servers=[{'url': 'https://api.zeit.co'}],
)


@app.get(
    '/v1/integrations/webhooks',
    tags=['webhook_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_webhooks(team_id: Optional[str] = Query(None, alias='teamId')):
    """
    Get a list of existent webhooks
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/integrations/webhooks',
    tags=['webhook_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_webhook(
    team_id: Optional[str] = Query(None, alias='teamId'),
    body: V1IntegrationsWebhooksPostRequest = ...,
):
    """
    Create a new webhook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/integrations/webhooks/:id',
    tags=['webhook_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_webhooks(team_id: Optional[str] = Query(None, alias='teamId')):
    """
    Remove a webhook by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v4/domains',
    tags=['domain_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_domains(team_id: Optional[str] = Query(None, alias='teamId')):
    """
    Gets a list of domains registered for the authenticating user.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v4/domains/{name}',
    tags=['domain_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_domain(name: str, team_id: Optional[str] = Query(None, alias='teamId')):
    """
    Get a domain for the authenticated user by name
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
